version: "3.8"
services:
  api:
    build: .
    ports:
      - "3333:3333"
    volumes:
      # Monta o código para desenvolver dentro do container (útil para utilizar `pnpm dev`)
      - ./:/app:cached
      - ./prisma:/app/prisma
    environment:
      NODE_ENV: development
    command: pnpm dev

  # Exemplo de serviço para banco (opcional)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: house
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

# volumes:
#   db-data:
